export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SUCCESS: 200,
  NOTFOUND: 404,
  SERVER_ERROR: 502,
  UNPROCESSABLE_ENTITY: 422,
}

export const MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  INVALID_TOKEN: 'Invalid token. Please log in again.',
  AUTH_REQUIRED: 'Authentication required.',
  ACCESS_DENIED: 'Access denied.',
  DATABASE_ERROR: 'Database error occurred.',
  INVALID_CREDENTIALS: 'Credentials not valid',
  USER_GET: 'User get successfully',
  CREATE_USER: 'Create user successfully',
  LOGIN_USER: 'Login user successfully',
  USER_UPDATE: 'Update user successfully',
  USER_DELETE: 'Delete user successfully',
  TOKENNOT_PROVED: 'You are not logged in! Please log in to get access.',
  TOKEN_EXPIRED: 'Invalid token. Please log in again.',
  UNAUTHORIZED: 'User not authorized',
  PASSWORD_CHANGED: 'Password changed successfully',
  SAME_PASSWORD_ERROR: 'Old password and new both are same',
  ALREADY_EXIST: 'User already exists',
  SERVER: 'Server error',
  EMAIL_SEND: 'Email send successfully',
  EMAIL_UPDATE_FORBIDDEN: 'Email Can,t we update',
  EMPTY_BODY: 'Please Provide at least one field',
  WRONG_PASSWORD: 'Please provide valid password',
}
